### ISSUE TITLE
currently lprint / pappl version (after 1.1.0) lost compatibility with cups 2.2.x

### ISSUE THREAD

**Issue by janwilmans** [michaelrsweet/lprint#67]
lprint (or actually pappl)  == v1.1.0 builds ok on debian 10 (buster) using CUPS v2.2.1

However, all versions after that do not, and I get this error:  (which makes sense because IPP_OP_CREATE_SYSTEM_SUBSCRIPTIONS never made it into a cups 2.2.x release.)

```
subscription-ipp.c: In function ‘_papplSubscriptionIPPCreate’:
subscription-ipp.c:120:189: error: ‘IPP_OP_CREATE_SYSTEM_SUBSCRIPTIONS’ undeclared (first use in this function); did you mean ‘IPP_OP_CREATE_PRINTER_SUBSCRIPTIONS’?
  120 |   if (ippGetOperation(client->request) == IPP_OP_CREATE_JOB_SUBSCRIPTIONS || ippGetOperation(client->request) == IPP_OP_CREATE_PRINTER_SUBSCRIPTIONS || ippGetOperation(client->request) == IPP_OP_CREATE_SYSTEM_SUBSCRIPTIONS)
      |                                                                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                                             IPP_OP_CREATE_PRINTER_SUBSCRIPTIONS
subscription-ipp.c:120:189: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [../Makedefs:75: subscription-ipp.o] Error 1
make: *** [Makefile:28: all] Error 1
```

**Comment by michaelrsweet** [comment]
@janwilmans PAPPL 1.2.1 fixes builds against versions of CUPS prior to 2.2.6.

**Comment by janwilmans** [comment]
So I guess to build lprint 1.1.0 using CUPS 2.2.x, I need to build against pappl 1.2.1 I will give that a try.

**Comment by janwilmans** [comment]
[f99d12f](https://github.com/michaelrsweet/pappl/commit/f99d12f436c13693856acd75644e6300d3348e95) (current master)

again, doesn't build against CUPS 2.2.x

Also `libgnutls28-dev` is missing from this list of dependencies:

https://github.com/michaelrsweet/pappl/blob/master/BUILD.md
![image](https://user-images.githubusercontent.com/5933444/179717129-d5833bab-f571-42a6-abda-68a975b7f630.png)

![image](https://user-images.githubusercontent.com/5933444/179717675-f75387c3-eabc-466f-8498-20b214c265e1.png)

![image](https://user-images.githubusercontent.com/5933444/179717733-ec712a6a-8110-4790-92ac-4d961f986757.png)

**Comment by michaelrsweet** [comment]
@janwilmans PAPPL supports both OpenSSL and GNU TLS. The BUILD.md dependencies list the OpenSSL package...

**Comment by janwilmans** [comment]
> @janwilmans PAPPL supports both OpenSSL and GNU TLS. The BUILD.md dependencies list the OpenSSL package...

Yes, you're right, I didn't re-run ./configure after installing OpenSSL , sorry about the false-positive
