### PR TITLE
Add Phomemo PM-241-BT to the TSPL driver list

### PR DESCRIPTION
**Pull request by codewiz**
This adds a driver list entry for the Phomemo PM-241-BT, a 4-inch
203dpi thermal label printer (USB ID 2e3c:5750) that speaks TSPL. The
existing TSPL driver code works with it unmodified.

The IEEE-1284 device ID reported by the printer is:

    MFG: ;CMD:XPP,XL;MDL:PM-241-BT;CLS:PRINTER;DES:PM-241-BT;

Note the blank MFG value, which is why the match string uses only MDL
and CMD.

Tested on the physical printer (Fedora 45, built from master with the
tspl changes cherry-picked onto v1.4.0 since CUPS 2.5 is not released
yet):

- lprint autoadd selects the new driver from the device ID
- printing PWG raster jobs through a CUPS "everywhere" queue
  (pdftopdf -> gstoraster -> IPP), including Japanese shipping labels
  with text, barcodes and QR codes
- raw TSPL jobs through the 9100 socket
- media sensing (GAP), density and feed behave correctly with the
  stock TSPL output

I own this printer and can test changes and help with any PM-241-BT
issues that get reported.

Assisted-by: Claude:claude-fable-5 [Claude Code]

### CODE REVIEW

**Comment by michaelrsweet** [comment]
We need to update the code to allow for a blank MFG value, otherwise we can incorrectly match a model from any manufacturer.

**Comment by codewiz** [comment]
Good point - updated. It turns out no code change is needed: papplDeviceParseID keeps an empty value for "MFG: ;", on both the device ID and the match string, so the match string can just require the blank MFG:

    "MFG:;MDL:PM-241-BT;CMD:XPP,XL;"

Scores from match_id() with that entry:

    device MFG: ;CMD:XPP,XL;MDL:PM-241-BT;...    -> 6
    device MFG:Acme;CMD:XPP,XL;MDL:PM-241-BT;... -> 0
    device MFG:Zebra Technologies;...            -> 0

so a same-model printer from a real manufacturer no longer matches.

**Comment by codewiz** [comment]
Is this ok to merge?

**Comment by michaelrsweet** [comment]
@codewiz Probably, I've been busy with other issues and haven't had a chance to get back to LPrint...

**Comment by codewiz** [comment]
I tried rebasing this PR onto master, but it no longer builds for me because lprint now depends on CUPS 2.5.

I'd rather not build the whole stack from sources, so I'll wait for Fedora Rawhide to catch up with cups 2.5.

**Comment by michaelrsweet** [comment]
@codewiz LPrint doesn't depend on CUPS 2.5 or later.

You might be confusing things with PAPPL master (what will one day become PAPPL 2.0) which needs CUPS 2.5 or later. PAPPL 1.4.x (which is what I build and ship binaries of LPrint against) works with CUPS 2.4 or later.

**Comment by codewiz** [comment]
@michaelrsweet I get these errors from git head:

```
bernie@giskard:~/src/lprint% make
Compiling lprint.c...
Compiling lprint-brother.c...
Compiling lprint-common.c...
Compiling lprint-cpcl.c...
Compiling lprint-dymo.c...
Compiling lprint-epl2.c...
Compiling lprint-escpos.c...
Compiling lprint-sii.c...
Compiling lprint-tspl.c...
Compiling lprint-zpl.c...
lprint-brother.c: In function ‘lprintBrother’:
lprint-brother.c:152:5: error: implicit declaration of function ‘cupsCopyString’; did you mean ‘papplCopyString’? [-Wimplicit-function-declaration]
  152 |     cupsCopyString(data->media_ready[0].size_name, "roll_dk2205-continuous_2.4x3.9in", sizeof(data->media_ready[0].size_name));
      |     ^~~~~~~~~~~~~~
      |     papplCopyString

[...]
```

Does lprint depend on libcups 3.0 now?

**Comment by codewiz** [comment]
Also, README.md says that LPrint depends on "CUPS 2.5 or later or libcups 3.0 or later".

Fedora packages neither at this time.

**Comment by michaelrsweet** [comment]
OK, I'll fix the documentation and the code which should not be depending on any newer CUPS APIs at this point since it is still PAPPL 1.4 or later...

**Comment by michaelrsweet** [comment]
[master 0dcb3a8] Fix builds against PAPPL 1.4.x and CUPS 2.4.x.

**Review by michaelrsweet — APPROVED** [review]
